name: Bandit Security Check
on: [push, pull_request]
jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Устанавливаем последнюю версию Python 3

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit
      run: bandit -r . -f txt -o bandit-report.txt # Производим рекурсивный анализ и сохраняем в текстовом формате

    - name: Upload Bandit Report as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: bandit-report
        path: bandit-report.txt
