name: Analyze Code

on: 
  push:
    branches: 
      - master

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit flake8 mypy pylint

    - name: Check for Bandit label
      id: bandit_label
      run: |
        echo "LABEL_FOUND=$(echo '${{ github.event.commits[0].message }}' | grep -qi 'bandit' && echo 'true' || echo 'false')" >> $GITHUB_ENV
      continue-on-error: true

    - name: Check for Flake8 label
      id: flake8_label
      run: |
        echo "LABEL_FOUND=$(echo '${{ github.event.commits[0].message }}' | grep -qi 'flake8' && echo 'true' || echo 'false')" >> $GITHUB_ENV
      continue-on-error: true

    - name: Check for Mypy label
      id: mypy_label
      run: |
        echo "LABEL_FOUND=$(echo '${{ github.event.commits[0].message }}' | grep -qi 'mypy' && echo 'true' || echo 'false')" >> $GITHUB_ENV
      continue-on-error: true

    - name: Check for Pylint label
      id: pylint_label
      run: |
        echo "LABEL_FOUND=$(echo '${{ github.event.commits[0].message }}' | grep -qi 'pylint' && echo 'true' || echo 'false')" >> $GITHUB_ENV
      continue-on-error: true

    - name: Run Bandit
      if: env.LABEL_FOUND == 'true'
      run: |
        bandit -r . -f json -o bandit_report.json

    - name: Run Flake8
      if: env.LABEL_FOUND == 'true'
      run: |
        flake8 --format=html --htmldir=flake8_report --output-file=flake8_report.txt

    - name: Run Mypy
      if: env.LABEL_FOUND == 'true'
      run: |
        mypy . > mypy_report.txt

    - name: Run Pylint
      if: env.LABEL_FOUND == 'true'
      run: |
        pylint $(git ls-files '*.py') --output-format=json > pylint_report.json
