name: Flake8

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' # Или любая другая версия Python, которую вы используете

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Flake8 and handle errors
        run: flake8 ./ --count --show-source --statistics > flake8_res.txt || true
        env:
          pythonLocation: /opt/hostedtoolcache/Python/3.9.19/x64
          LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.19/x64/libt
          
      - name: Upload Flake8 results
        uses: actions/upload-artifact@v2
        with:
         name: flake8-results
         path: flake8_results.txt
