name: "Mypy"
on:
  pull_request: {}
  push:
      branches: ["master"]

jobs:
  run_mypy:
    runs-on: ubuntu-latest
    name: Mypy
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Mypy
        continue-on-error: true  # Чтобы the workflow продолжился даже если mypy найдет ошибки
        uses: jashparekh/mypy-action@v2
        with:
          path: '.'
          mypy_version: '0.910'
          #mypy_flags: '--verbose'
          #mypy_config_file: 'mypy.ini'
          #requirement_files: 'requirements.txt'
