name: Type Checking with mypy

on: [push, pull_request]

jobs:
  mypy:
    name: Run mypy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Укажите нужную версию Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy  # Install mypy
          # Дополнительные зависимости можно добавить здесь, если они нужны для вашего проекта

      - name: Type check
        continue-on-error: true  # Чтобы the workflow продолжился даже если mypy найдет ошибки
        run: mypy . --no-incremental --txt-report mypy-report.txt  # Сохраняем отчет в директории mypy-report

      - name: Archive mypy results
        uses: actions/upload-artifact@v2
        with:
          name: mypy-results
          path: mypy-report.txt
