name: "Mypy"
on:
  pull_request: {}
  push:
      branches: ["master"]

jobs:
  run_mypy:
    runs-on: ubuntu-latest
    name: Mypy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: python -m pip install mypy==0.910
      - name: Run Mypy
        continue-on-error: true  # Продолжить даже если mypy найдет ошибки
        run: mypy . | tee mypy_output.txt
      - name: Upload Mypy Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: mypy-results
          path: mypy_output.txt
