name: Python Linting

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Find and lint all Python files
      run: |
        git ls-files '*.py' -z | xargs -0 -n 1 -I {} bash -c 'file="$1"; pylint "${file##*/}"' _ {}
    - name: Upload pylint report
      uses: actions/upload-artifact@v2
      with:
        name: pylint-report
        path: pylint-report.txt
